---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/don_quixote/don_quixote.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/170837/articles/296640/master/file/figures/don_quixote/don_quixote.png"
    folder_url: "/users/170837/articles/296640/master/folder/figures/don_quixote"
